version: '3'
services:
  postgres:
    image: mdillon/postgis:9.6
    container_name: svc_db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - svc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

  web:
    # image: 'node:10.16-alpine'
    build: '.'
    container_name: svc_web
    working_dir: /app
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - postgres
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ${PATH_PREFIX}:/app
    environment:
      NODE_ENV: development

  npm:
    # image: 'node:10.16-alpine'
    build: '.'
    container_name: svc_npm
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ${PATH_PREFIX}:/app
    environment:
      NODE_ENV: development

  nest:
    # image: 'node:10.16-alpine'
    build: '.'
    container_name: svc_nest
    working_dir: /app
    entrypoint: ['nest']
    volumes:
      - ${PATH_PREFIX}:/app
    environment:
      NODE_ENV: development

volumes:
  svc_data:
    external: true
